services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - "caddy_data:/data/caddy"
      - "caddy_config:/config"
      - "./logs/caddy2:/var/log/caddy"
      - "./conf/caddy2/Caddyfile.wp:/etc/caddy/Caddyfile"
      - "wordpress_data:/var/www/html"

  wordpress:
    container_name: wordpress
    image: wordpress:php8.3-fpm-alpine
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      "./env/wordpress.env"
    volumes:
      - "wordpress_data:/var/www/html"
      - "./conf/wordpress/custom.ini:/usr/local/etc/php/conf.d/uploads.ini"

  mariadb:
    container_name: mariadb
    image: mariadb:lts-ubi9
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "./conf/mariadb/healthcheck.sh:/usr/local/bin/healthcheck.sh"
    restart: unless-stopped
    env_file:
      - "./env/mariadb.env"

volumes:
  mariadb_data:
  wordpress_data:
  caddy_data:
  caddy_config:
  portainer_data:

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
    internal: true
